# Generated by Django 4.2.7 on 2024-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
